# Generated by Django 6.0 on 2025-12-28 11:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterCardInfo',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=128)),
                ('credit_limit_min', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Credit limit (min)')),
                ('credit_limit_max', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Credit limit (max)')),
                ('no_rate_period', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Grace period (days)')),
                ('gdr', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Annual interest rate (%)')),
                ('year_tax', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Annual fee')),
                ('is_default', models.BooleanField(default=False, help_text='Which card loads by default')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='MasterCardsContainer',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
